1. Create a vector with values ranging from 10 to 49.

In [8]:
import numpy as np
b=np.arange(10,50) 
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3x3 matrix with values ranging from 0 to 8.

In [10]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
matrix = np.arange(100).reshape(10, 10)
print(matrix)
min=np.min(matrix)
print("The min value is:",min)
max=np.max(matrix)
print("The max value is:",max)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
The min value is: 0
The max value is: 99


4. Create a random vector of size 30 and find the mean value.

In [12]:
vector = np.random.random(30)
meanvalue = np.mean(vector)
print("Mean value is:", meanvalue)

Mean value is: 0.4189251986776363


5. Perform addition, subtraction, multiplication, and division of two given NumPy arrays.

In [13]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
# Addition
addition= array1 + array2
# Subtraction
subtraction= array1 - array2
# Multiplication
multiplication= array1 * array2
# Division
division= np.divide(array1, array2)                    
print("Addition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


6. Calculate the element-wise square root of a given NumPy array.

In [14]:
array = np.array([[4, 9], [16, 25]])
sqrt= np.sqrt(array)
print("Element-wise square root:")
print(sqrt)

Element-wise square root:
[[2. 3.]
 [4. 5.]]


7. Stack two given arrays vertically and horizontally.

In [15]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
verticalstack = np.vstack((array1, array2))
horizontalstack = np.hstack((array1, array2))
print("Stack vertically:")
print(verticalstack)
print("\nStack horizontally:")
print(horizontalstack)

Stack vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Stack horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


8. Reshape a given 1D array into a 2D array with 3 rows and 4 columns.

In [16]:
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array2d = array1d.reshape(3, 4)
print("Original 1D array:")
print(array1d)
print("\nReshaped 2D array:")
print(array2d)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


9. Transpose a given 2D array and then flatten it into a 1D array.

In [17]:
array= np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
transposedarray = array
flattened= transposedarray.flatten()
print("Original 2D array:")
print(array)
print("\nTransposed array:")
print(transposedarray)
print("\nFlattened 1D array:")
print(flattened)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D array:
[1 2 3 4 5 6 7 8 9]


10. Create a random of array and implement different slicing methods on it.

In [18]:
import numpy as np
randomarray = np.random.randint(1, 100, size=(5, 5))
print("Random Array:")
print(randomarray)
print()
slice_1 = randomarray[1:4, 1:4]
print(slice_1)
print()
slice_2 = randomarray[::2, ::2]
print(slice_2)
print()
slice_3 = randomarray[-3:-1, -3:-1]
print(slice_3)
print()

Random Array:
[[88 59 41 92 98]
 [ 4 63 34 93 93]
 [ 1 63 65 67 27]
 [86 16 95 81  5]
 [69 70  9 85  9]]

[[63 34 93]
 [63 65 67]
 [16 95 81]]

[[88 41 98]
 [ 1 65 27]
 [69  9  9]]

[[65 67]
 [95 81]]

